#!/usr/bin/env python3
"""
Concatenates every table HTML file under docs/schema-<version>/schema/tables/
into a single all_tables_combined.html next to it. Stdlib only.

Usage:
    python tools/build_combined_html.py [schema-version-dir]

If no directory is given, the newest docs/schema-* directory is used.
"""

import sys
from pathlib import Path

from build_schema_json import find_schema_dir


def write(schema_dir: Path) -> Path:
    root = schema_dir / "schema"
    tables_dir = root / "tables"
    out_path = root / "all_tables_combined.html"

    files = sorted(tables_dir.rglob("*.html"), key=lambda p: p.as_posix())
    parts = [
        "<!-- Combined Blackboard LMS schema tables -->",
        "<!-- Auto-generated by tools/build_combined_html.py -->",
        f"<!-- Source root: {tables_dir.relative_to(root.parent.parent.parent).as_posix()} -->",
        "",
    ]
    for f in files:
        parts += ["", f"<!-- FILE:{f.relative_to(root).as_posix()} -->"]
        parts.append(f.read_text(encoding="utf-8", errors="replace").rstrip("\n"))
        parts.append("")

    out_path.write_text("\n".join(parts) + "\n", encoding="utf-8", newline="\n")
    print(f"Combined {len(files)} table files into {out_path}")
    return out_path


def main() -> None:
    write(find_schema_dir(sys.argv[1] if len(sys.argv) > 1 else None))


if __name__ == "__main__":
    main()
